version: '3.8'

services:
  catalog:
    restart: always
    build: Catalog
    command: /Catalog/api/
    ports:
      - 4000:4000
  ordering:
    restart: always
    build: Ordering
    command: /Ordering/api
    ports:
      - 4001:4001
  users:
    restart: always
    build: Users
    command: /Users/api
    ports:
      - 4002:4002